/**
 * G-Tags configuration and default labels
 */
/*jslint nomen: true*/
var gtc=
{
filtered:['UA-32455356-5'],
clic:[],
type:['utmt','Type','dc:Doubleclick'],
typeU:['t','Type','dc:Doubleclick'],
headers: [['utmac','site'],['tid','site'],['utmdt','title'],['dt','title']],
hclic:[],
hother:[],
hpage:[],
rparams :[['utme', 'Extensible'],['ec', 'Category'],['ea','Action'],['el','Label'],['ev','Value']],
pcustoms:[],
label:
{
_r:'Redirected request',
_s:'Hit sequence',
_u:'Verification code',
_utma:'Visitor cookie',
_utmb:'Session cookie',
_utmc:'Session cookie',
_utmht:'Cookie value',
_utmv:'Custom variable cookie',
_utmz:'Campaign cookie',
_v:'SDK Version',
a:'Adsense link',
an:'Application name',
aid:'Application ID',
aiid:'Application installation ID',
aip:'Anonymize IP',
av:'Application version',
cc:'Campaign content',
cd:'Screen name',
cd_I_:'Custom dimension $0',
cg_I_:'Custom group $0',
ci:'Campaign ID',
cid:'Anonymous Client ID',
ck:'Campaign keyword',
clt:'Content load time',
cm:'Campaign medium',
cm_I_:'Custom metric $0',
cn:'Campaign name',
col:'Checkout step number',
cos:'Checkout step name',
cs:'Campaign source',
cu:'Currency',
dclid:'Display ads ID',
de:'Document encoding',
dh :'Host name',
dit:'DOM interactive time',
dl:'Document location',
dns:'DNS time',
dp:'Path',
dr:'Document referrer',
ds:'Data source',
dt:'Title',
exd:'Exception description',
exf:'Exception fatal?',
fl:'Flash version',
geoid:'Geographical override',
glcid:'Adwords ID',
gtm:'Google Tag Manager container',
ic:'Item code',
il_I_nm:'Product impression list $0 name',
il_I_pi_I_br:'List $0 Product $1 impression brand',
il_I_pi_I_ca:'List $0 Product $1 impression category',
il_I_pi_I_cd_I_:'List $0 Product $1 impression custom dimension $2',
il_I_pi_I_cm_I_:'List $0 Product $1 impression custom metric $2',
il_I_pi_I_id:'List $0 Product $1 impression ID or SKU',
il_I_pi_I_nm:'List $0 Product $1 impression name',
il_I_pi_I_pr:'List $0 Product $1 impression price',
il_I_pi_I_ps:'List $0 Product $1 impression position',
il_I_pi_I_va:'List $0 Product $1 impression variant',
'in':'Item name',
ip:'Item unit price',
iq:'Item quantity',
iv:'Item variation',
je:'Java enabled?',
jid:'Join ID GA/Doubleclick',
linkid:'Clicked DOM element ID',
ni:'Non interaction',
pa:'Product action',
pdt:'Page download time',
plt:'Page load time',
pr_I_ca:'Product $0 category',
pr_I_cd_I_:'Product $0 custom dimension $1',
pr_I_cm_I_:'Product $0 custom metric $1',
pr_I_id:'Product $0 ID or SKU',
pr_I_nm:'Product $0 name',
pr_I_pr:'Product $0 price',
pr_I_qt:'Product $0 quantity',
pr_I_va:'Product $0 variant',
promo_I_cr:'Promotion $0 creative',
promo_I_id:'Promotion $0 ID',
promo_I_nm:'Promotion $0 name',
promo_I_ps:'Promotion $0 position',
qt:'Queue time',
rrt:'Redirect response time',
sa:'Social action',
sc:'Session control',
sd:'Screen color depth',
sn:'Social network name',
sr:'Screen resolution',
srt:'Server response time',
st:'Social destination',
t:'Tracking type',
ta:'Transaction affiliation',
tcc:'Transaction coupon',
tcp:'TCP connect time',
ti:'Transaction ID',
tr:'Transaction revenue',
ts:'Transaction shipping',
tt:'Transaction tax',
ua:'User agent override',
uid:'Known user ID',
uip:'User IP override',
ul:'User language',
utc:'Timing category',
utl:'Timing label',
utmac:'Account',
utmcc:'Visitor and Campaign cookies',
utmccn:'Campaign name',
utmcct:'Campaign content',
utmcmd:'Campaign medium',
utmcn:'New campaign?',
utmcr:'Repeat campaign?',
utmcs:'Document encoding',
utmcsr:'Campaign source',
utmctr:'Campaign keyword',
utmdt:'Document title',
utme:'Extensible',
utmfl:'Flash version',
utmhid:'Cache buster',
utmhn:'Host name',
utmht:'Timestamp',
utmipc :'Item code',
utmipn:'Item name',
utmipr:'Item unit price',
utmiqt:'Item quantity',
utmiva:'Item variation',
utmje:'Java enabled?',
utmjid:'Join ID GA/Doubleclick',
utmn:'Cache buster',
utmp:'Document path',
utmr:'Document referrer',
utmredir:'Redirected request',
utms:'Hit sequence',
utmsa:'Social action',
utmsc:'Screen color depth',
utmsid:'Social destination',
utmsn:'Social network name',
utmsr:'Screen resolution',
utmt:'Tracking type',
utmtci:'Billing city',
utmtco:'Billing country',
utmtid:'Transaction ID',
utmtrg:'Billing region',
utmtsp:'Transaction shipping',
utmtst:'Transaction affiliation',
utmtto:'Transaction revenue',
utmttx:'Transaction tax',
utmu:'Verification code',
utmul:'Browser language',
utmvp:'Viewport resolution',
utmwv:'SDK version',
utt:'Timing time',
utv:'Timing variable',
v:'Protocol version',
vp:'Viewport resolution',
xid:'Experiment ID',
xvar:'Experiment variant',
z:'Cache buster'
}
};