var gt={browser:window.chrome||window.browser,record:!0,timeout:0,translate:!0,lastSite:0,timer:null,aufilter:"*://*.google-analytics.com/__utm.gif* *://*.google-analytics.com/r* *://*.google-analytics.com/collect* *://stats.g.doubleclick.net/__utm.gif* *://stats.g.doubleclick.net/collect* *://stats.g.doubleclick.net/r*".split(" "),apirest:"",apiauth:"",rqdone:{},getUrlParser:function(b){var a={};b.replace(RegExp("([^?=&]+)(=([^&]*))?","g"),function(b,d,e,g){a[d.toLowerCase()]=g});return a},getUrl:function(b){return/(?:https?:\/\/)?(.*)$/i.exec(b)[1]},
getTitle:function(b){return(1<b.length&&gt.translate?b[1]:"")||b[0]},getParamLabel:function(b){var a=(gtc.label[b]||b).replace(/ /g,"&nbsp;"),c=[],d=b,e=0;if(a===b&&(c=b.match(/[0-9]+/g))&&c.length){for(e=0;e<c.length;e++)d=d.replace(c[e],"_I_");if(a=gtc.label[d]){for(e=0;e<c.length;e++)a=a.replace("$"+e.toString(),c[e]);a=a.replace(/ /g,"&nbsp;")}else a=b}return a},getValue:function(b,a){var c=b[a[0]],d=0,e=[];if(c){c=decodeURIComponent(c);if(2<=a.length&&("site"===a[1]&&(gt.lastSite=c),2<a.length&&
gt.translate)){gt.translate=!1;for(d=2;d<a.length;d++)if(e=a[d].split(":"),2===e.length&&("*"===e[0]||e[0]===c.toLowerCase())){c="-"===e[1].charAt(0)?c+" - "+e[1].substr(1):e[1];gt.translate=!0;break}}b[a[0]]=null}return"undefined"===c?"":c},getCheckSetting:function(b,a){var c=localStorage[b];return c?"1"===c?!0:!1:a},recordChanged:function(){gt.record&&!gt.timer?gt.timer=window.setInterval(gt.onTimer,1E3):gt.timer&&(window.clearInterval(gt.timer),gt.timer=null)},onClickRecord:function(){this.classList.toggle(gtr.cnActive);
gt.record=0<=this.className.indexOf(gtr.cnActive);this.title=gt.record?gtr.sStop:gtr.sResume;gt.recordChanged()},allCheckChanged:function(b,a,c,d){a=document.querySelectorAll(a);for(var e=0,e=0;e<a.length;e++)a[e].style.display=b.checked&&(d||a[e].textContent.replace(/(^\s*)/g,""))?c||"block":gtr.vNone;localStorage[b.id]=b.checked?"1":"0"},typeCheckChanged:function(b,a){gt.allCheckChanged(b,"."+gtr.cnRq+"."+a,gtr.vRow);gtr.cbDetails.checked&&gt.allCheckChanged(b,"."+a+"."+gtr.cnInfo+(gtr.cbAdvanced.checked?
"":"."+gtr.cnDetail),gtr.vRow)},infosCheckChanged:function(b,a){gtr.cbPage.checked&&gt.allCheckChanged(b,"."+gtr.cnPage+a,gtr.vRow);gtr.cbClic.checked&&gt.allCheckChanged(b,"."+gtr.cnClic+a,gtr.vRow);gtr.cbOther.checked&&gt.allCheckChanged(b,"."+gtr.cnOther+a,gtr.vRow)},detailsCheckChanged:function(b){var a=gtr.cbAdvanced;b||(a.checked=!1);a.disabled=!b},onCheckPage:function(){gt.typeCheckChanged(this,gtr.cnPage)},onCheckClick:function(){gt.typeCheckChanged(this,gtr.cnClic)},onCheckOther:function(){gt.typeCheckChanged(this,
gtr.cnOther)},onCheckUrl:function(){gt.allCheckChanged(this,"."+gtr.cnUrl,gtr.vCell,!0)},onCheckDetails:function(){gt.infosCheckChanged(this,this.checked?"."+gtr.cnInfo+"."+gtr.cnDetail:"."+gtr.cnInfo);gt.detailsCheckChanged(this.checked)},onCheckAdvanced:function(){gt.infosCheckChanged(this,"."+gtr.cnInfo+"."+gtr.cnAdvanced)},onClickCopy:function(){for(var b=document.querySelectorAll("."+gtr.cnRq),a=0,c=0,d="",e=[],a=0;a<b.length;a++)if(b[a].style.display===gtr.vRow){e=b[a].querySelectorAll("th");
for(c=0;c<e.length;c++)d+=e[c].textContent+(c<e.length-1?"\t":"\r\n")}d&&(gt.browser.runtime.sendMessage({type:"copy",text:d}),alert(gtr.sCopyDone))},onClickClear:function(){gtr.dTags.innerHTML=""},onClickChevron:function(b){gt.toggleBar(!1);b.stopPropagation();return!1},onClickBar:function(){"false"===localStorage.visibleBar&&gt.toggleBar(!0)},onDoubleClickBar:function(){"true"===localStorage.visibleBar&&gt.toggleBar(!1)},onLoad:function(){var b=0,a="cbPage cbClic cbUrl cbOther cbDetails cbAdvanced".split(" ");
gtr.bind();for(b=0;b<a.length;b++)gtr[a[b]].checked=gt.getCheckSetting(gtr[a[b]].id,gtr[a[b]].checked);gt.detailsCheckChanged(gtr.cbDetails.checked);gtr.cbPage.onchange=gt.onCheckPage;gtr.cbClic.onchange=gt.onCheckClick;gtr.cbUrl.onchange=gt.onCheckUrl;gtr.cbOther.onchange=gt.onCheckOther;gtr.cbDetails.onchange=gt.onCheckDetails;gtr.cbAdvanced.onchange=gt.onCheckAdvanced;gtr.btCopy.addEventListener("click",gt.onClickCopy);gtr.btClear.addEventListener("click",gt.onClickClear);gtr.dRecord.addEventListener("click",
gt.onClickRecord);gtr.dBar.addEventListener("click",gt.onClickBar);gtr.dBar.addEventListener("dblclick",gt.onDoubleClickBar);gtr.dChevron.addEventListener("click",gt.onClickChevron);"false"===localStorage.visibleBar&&setTimeout(function(){gt.toggleBar(!1)},1E3);gt.recordChanged()},onResize:function(){gt.timeout&&clearTimeout(gt.timeout);gt.timeout=setTimeout(function(){gt.browser.runtime.sendMessage({type:"resize"});gt.timeout=0},100)},toggleBar:function(b){b?(gt.rheight=gtr.dBar.clientHeight,gtr.dBar.classList.remove(gtr.cnReduced),
setTimeout(function(){gtr.dContent.scrollTop+=gtr.dBar.clientHeight-gt.rheight+1},300)):gtr.dBar.classList.add(gtr.cnReduced);gtr.dBar.title=b?"":gtr.sExpand;localStorage.visibleBar=b},onDoubleClickTag:function(b){var a=this.nextSibling,c=0,d=[],e=!1;if(a&&(d.push(a),e=a.style.display!==gtr.vNone,a=a.nextSibling))d.push(a),e=a.style.display!==gtr.vNone;e=!e;for(c=0;c<d.length;c++)d[c].style.display=e&&d[c].textContent.replace(/(^\s*)/g,"")?gtr.vRow:gtr.vNone;window.getSelection?window.getSelection().removeAllRanges():
document.selection&&document.selection.empty();b.preventDefault();b.stopPropagation();return!1},addRequest:function(b,a){gt.rqdone[b.requestId]={requestId:b.requestId,tabId:b.tabId,url:b.url,timeStamp:b.timeStamp,tabUrl:a,done:!1}},isFiltered:function(b){var a=0;b=b.split(" ");for(a=0;a<gtc.filtered.length;a++)if(b[0]===gtc.filtered[a])return!0;return!1},addTag:function(b){gt.rqdone[b.requestId].done=!0;var a=null,c="",d=0,e=0,g="",k=null,h=gt.getUrlParser(b.url),n=!0,l=[],f="",j="",a=new Date(b.timeStamp),
l=h.tid?!0:!1,p=!1,f="event"===h.t||"event"===h.utmt,j=!f&&(h.t&&"pageview"!==h.t||h.utmt&&"page"!==h.utmt),m=f&&gtr.cbClic.checked||j&&gtr.cbOther.checked||!f&&!j&&gtr.cbPage.checked,t=gtr.cbUrl.checked,q=gtr.cbDetails.checked,r=!1,s=!1,d="";gt.detailsCheckChanged(q);r=gtr.cbAdvanced.checked;gt.translate=!0;d=j&&!f?h.utmt?gt.getValue(h,gtc.type):h.t?gt.getValue(h,gtc.typeU):gtr.sOther:gtr.sPage;c=c+'<th style="text-transform:capitalize;"><b>'+((f?gtr.sClick+"&nbsp;</b>":d+"</b>")+"</th>");gt.translate=
!0;for(e=d=0;d<gtc.headers.length&&2>e;d++){g=gt.getValue(h,gtc.headers[d]);if("site"===gtc.headers[d][1]){if(g&&gt.isFiltered(g))return;s=gt.translate;g&&(p=!0,l&&(g=g.replace("UA","<b>UA</b>")),g=g.replace(/-/g,"&#8209;"))}g&&(c+='<th class="'+gtc.headers[d][1]+'">'+g+"</th>",e++)}if(p){for(d=e;1>d;d++)c+="<th></th>",e++;l=f?gtc.hclic:j?gtc.hother:gtc.hpage;gt.translate=!0;for(d=0;d<l.length;d++)if(g=gt.getValue(h,l[d])){c+="<th>"+g+"</th>";e++;break}for(d=e;2>d;d++)c+="<th></th>",e++;c+='<th class="url" style="display:'+
(t?gtr.vCell:gtr.vNone)+';">'+(f?"":gt.getUrl(b.tabUrl))+"</th>";c+='<th class="time">'+a.toLocaleTimeString().replace(/ /g,"&nbsp;")+"</th>";j=f?gtr.cnClic:j?gtr.cnOther:gtr.cnPage;a=document.createElement("tr");a.style.display=m?gtr.vRow:gtr.vNone;a.className="request "+j;a.title=gtr.sDoubleclic;a.innerHTML=c;gtr.dTags.appendChild(a);a.addEventListener("dblclick",gt.onDoubleClickTag);a=document.createElement("tr");a.className=j+" "+gtr.cnInfo+" "+gtr.cnDetail;c='<td colspan="6" class="detail"><span class="treechild"></span>';
gt.translate=!0;e=d=0;for(f="";d<gtc.rparams.length;d++)if(g=gt.getValue(h,gtc.rparams[d]))f+=(0<e?"&ensp;":"")+'<span style="display:inline-block;"><span class="tooltip"><b>'+gt.getTitle(gtc.rparams[d])+'</b><span class="tooltiptext tooltip-right">'+gtc.rparams[d][0]+"</span></span>:&nbsp;"+g+"</span>",e++;gt.translate=s;for(d=0;d<gtc.pcustoms.length;d++)if(g=gt.getValue(h,gtc.pcustoms[d]))f+=(0<e?"&ensp;":"")+"<b>"+gt.getTitle(gtc.pcustoms[d])+"</b>:&nbsp;"+g,e++;a.style.display=m&&q&&f?gtr.vRow:
gtr.vNone;c+=f+"</td>";a.innerHTML=c;gtr.dTags.appendChild(a);a=document.createElement("tr");a.className=j+" "+gtr.cnInfo+" "+gtr.cnAdvanced;c=f?'<td colspan="6" class="detail"><span class="treechild deep"></span>':'<td colspan="6" class="detail"><span class="treechild"></span>';f="";e=0;for(k in h)if(h.hasOwnProperty(k)&&(g=h[k]))f+=(0<e&&!n?"&ensp;":"")+'<span style="display:inline-block;"><span class="tooltip"><b>'+k+'</b><span class="tooltiptext tooltip-right">'+gt.getParamLabel(k)+"</span></span>:&nbsp;"+
decodeURIComponent(g)+"</span>",n=!1,e++;a.style.display=m&&r&&f?gtr.vRow:gtr.vNone;c+=f+"</td>";a.innerHTML=c;gtr.dTags.appendChild(a);gtr.dContent.scrollTop=gtr.dContent.scrollHeight;m&&gt.browser.runtime.sendMessage({type:"newtag"})}},onTimer:function(){if(gt.record){var b="",a=null,c=new Date,a=0,d=[];for(b in gt.rqdone)gt.rqdone.hasOwnProperty(b)&&(a=gt.rqdone[b],a.done?d.push(b):1E3<c-a.timeStamp&&gt.addTag(a));for(a=0;a<d.length;a++)delete gt.rqdone[d[a]]}},onSendHeaders:function(b){gt.record&&
(gt.rqdone[b.requestId]||gt.browser.tabs.get(b.tabId,function(a){gt.addRequest(b,a.url)}))},onHeadersReceived:function(b){if(gt.record){var a="",c=null;for(a in gt.rqdone)if(gt.rqdone.hasOwnProperty(a)&&a!==b.requestId&&(c=gt.rqdone[a])&&!c.done&&c.tabId===b.tabId){gt.addTag(c);break}(c=gt.rqdone[b.requestId])&&!c.done&&(200===b.statusCode||302===b.statusCode?gt.addTag(c):console.log("G-Tags >> "+b.url+" has returned status code:"+b.statusCode.toString()))}}};window.addEventListener("load",gt.onLoad);
window.addEventListener("resize",gt.onResize,!1);gt.browser.webRequest.onSendHeaders.addListener(gt.onSendHeaders,{urls:gt.aufilter});gt.browser.webRequest.onHeadersReceived.addListener(gt.onHeadersReceived,{urls:gt.aufilter});
