/**
 * X-Tags settings and default labels
 */
/*jslint nomen: true*/
var ts=
{
/** Header line */
header:
{
    type:
    {
        page:['utmt|t','','pageview:Page'],
        cta:['utmt|t'],    
        other:['utmt|t','','dc:Display advertising']        
    },
    space:[['utmac'],['tid']], // Mandatory
    spsub:[['ec']], // Optional
    /** Column Name: [param, contextual name] */
    name:
    {
        page:[['utmdt'],['dt']],
        cta:[['utme'],['el']], 
        other:[['utmdt'],['dt']]
    },
    compl:[['ea']]  // Optional
},
/**
 * Detail line 
 */
detail:
{
    /** Custom variables: [param, name when known site, value translation] */
    cvar:
    {
        max:30,    
        prefix:'cd',
        val:{}
    },
    /** Recognized parameters: : [param, (ignored), value translation] */
    other:[['utme'],['el'],['ev'],['pa'],['pr1id'],['pr1nm'],['pr1ca']]       
},

/** Space dictionary */
space:
{
    filtered:['UA-10005-44','UA-60390233-3','UA-32455356-5','UA-38676921-1','UA-38676921-2','UA-38676921-3','UA-38676921-4','UA-38676921-5','UA-38676921-6','UA-32455356-5','UA-10005-1','UA-25279800-1'],
    known:[]
},
/** Parameters dictionary */
param:
{   
_gid:'MD5 hash of page path',
_r:'Redirected request',
_s:'Hit sequence',
_u:'Verification code',
_utma:'Visitor cookie',
_utmb:'Session cookie',
_utmc:'Session cookie',
_utmht:'Cookie value',
_utmv:'Custom variable cookie',
_utmz:'Campaign cookie',
_v:'SDK Version',
a:'Adsense link',
an:'Application name',
aid:'Application ID',
aiid:'Application installation ID',
aip:'Anonymize IP',
av:'Application version',
cc:'Campaign content',
cd:'Screen name',
cd_:'Custom dimension',
cg_:'Custom group',
ci:'Campaign ID',
cid:'Anonymous Client ID',
ck:'Campaign keyword',
clt:'Content load time',
cm:'Campaign medium',
cm_I_:'Custom metric $0',
cn:'Campaign name',
col:'Checkout step number',
cos:'Checkout step name',
cs:'Campaign source',
cu:'Currency',
dclid:'Display ads ID',
de:'Document encoding',
dh :'Host name',
dit:'DOM interactive time',
dl:'Document location',
dns:'DNS time',
dp:'Path',
dr:'Document referrer',
ds:'Data source',
dt:'Page title',
ea:'Event Action',
ec:'Event Category',
el:'Event Label',
ev:'Value',
exd:'Exception description',
exf:'Exception fatal?',
fl:'Flash version',
geoid:'Geographical override',
glcid:'Adwords ID',
gtm:'Property managed in GTM',
ic:'Item code',
il_I_nm:'Product impression list $0 name',
il_I_pi_I_br:'List$0 Product$1 impression Brand',
il_I_pi_I_ca:'List$0 Product$1 impression Category',
il_I_pi_I_cd_I_:'List$0 Product$1 impression Custom dimension $2',
il_I_pi_I_cm_I_:'List$0 Product$1 impression Custom metric $2',
il_I_pi_I_id:'List$0 Product$1 impression SKU',
il_I_pi_I_nm:'List$0 Product$1 impression Name',
il_I_pi_I_pr:'List$0 Product$1 impression Price',
il_I_pi_I_ps:'List$0 Product$1 impression Position',
il_I_pi_I_va:'List$0 Product$1 impression Variant',
'in':'Item name',
ip:'Item unit price',
iq:'Item quantity',
iv:'Item variation',
je:'Java enabled?',
jid:'Join ID GA/Doubleclick',
linkid:'Clicked DOM element ID',
ni:'Non interaction',
pa:'Product Action',
pdt:'Page download time',
plt:'Page load time',
pr_I_br:'Product$0 Brand',
pr_I_ca:'Product$0 Category',
pr_I_cd_I_:'Product$0 Custom dimension $1',
pr_I_cm_I_:'Product$0 Custom metric $1',
pr_I_id:'Product$0 SKU',
pr_I_nm:'Product$0 Name',
pr_I_pr:'Product$0 Price',
pr_I_qt:'Product$0 Quantity',
pr_I_va:'Product$0 Variant',
promo_I_cr:'Promotion$0 Creative',
promo_I_id:'Promotion$0 ID',
promo_I_nm:'Promotion$0 Name',
promo_I_ps:'Promotion$0 Position',
qt:'Queue time',
rrt:'Redirect response time',
sa:'Social Action',
sc:'Session control',
sd:'Screen color depth',
sn:'Social network name',
sr:'Screen resolution',
srt:'Server response time',
st:'Social destination',
t:'Tracking type',
ta:'Transaction affiliation',
tcc:'Transaction coupon',
tcp:'TCP connect time',
ti:'Transaction ID',
tid:'Universal Analytics property',
tr:'Transaction Revenue',
ts:'Transaction Shipping',
tt:'Transaction Tax',
ua:'User agent override',
uid:'Known user ID',
uip:'User IP override',
ul:'User language',
utc:'Timing category',
utl:'Timing label',
utmac:'Google Analytics property',
utmcc:'Visitor and Campaign cookies',
utmccn:'Campaign name',
utmcct:'Campaign content',
utmcmd:'Campaign medium',
utmcn:'New campaign?',
utmcr:'Repeat campaign?',
utmcs:'Document encoding',
utmcsr:'Campaign source',
utmctr:'Campaign keyword',
utmdt:'Page title',
utme:'Extensible',
utmfl:'Flash version',
utmhid:'Cache buster',
utmhn:'Host name',
utmht:'Timestamp',
utmipc :'Item Code',
utmipn:'Item Name',
utmipr:'Item unit Price',
utmiqt:'Item Quantity',
utmiva:'Item Variation',
utmje:'Java enabled?',
utmjid:'Join ID GA/Doubleclick',
utmn:'Cache buster',
utmp:'Document path',
utmr:'Document referrer',
utmredir:'Redirected request',
utms:'Hit sequence',
utmsa:'Social action',
utmsc:'Screen color depth',
utmsid:'Social destination',
utmsn:'Social network name',
utmsr:'Screen resolution',
utmt:'Tracking type',
utmtci:'Billing city',
utmtco:'Billing country',
utmtid:'Transaction ID',
utmtrg:'Billing region',
utmtsp:'Transaction shipping',
utmtst:'Transaction affiliation',
utmtto:'Transaction revenue',
utmttx:'Transaction tax',
utmu:'Verification code',
utmul:'Browser language',
utmvp:'Viewport resolution',
utmwv:'SDK version',
utt:'Timing time',
utv:'Timing variable',
v:'Protocol version',
vp:'Viewport resolution',
xid:'Experiment ID',
xvar:'Experiment variant',
z:'Cache buster'
}
};