/**
 * XTag settings and default labels for adressed platform (GA)
 */
/*jslint nomen: true*/
var ts=
{
/** 
 * Header line 
 */
header:
{
    type:
    {
        page:['utmt|t|en','','pageview:Page','page_view:Page'],
        cta:['utmt|t'],    
        other:['utmt|t','','dc:Display Ads']        
    },
    /** Column Space: Google Analytics property - Mandatory */
    space:[['utmac'],['tid']],
    /** Column SpaceSub: Event category (UA) or Event Name (GA4) - Optional */
    spsub:[['ec'],['en']],
    /** Column Complement: Event action (UA) or Event parameter (GA4) - Optional */
    compl:[['ea'],['ep.link_classes'],['ep.link_text'],['epn.percent_scrolled'],['epn.video_percent']],  // Optional
    /** Column Name: [param, contextual name] */
    name:
    {
        page:[['utmdt'],['dt']],
        cta:[['utme'],['el'],['ep.link_url'],['epn.value'],['ep.menu_type']], 
        other:[['utmdt'],['doubleclick'],['dt']]
    },
    rowLabels:'Type\tProperty\tInfo_1\tInfo_2\tInfo_3\tURL\tTime\tQuery'
 },
/**
 * Detail line 
 */
detail:
{
    /** Custom variables: [param, name when known site, value translation] */
    cvar:
    {
        max:30,    
        prefix:'cd',
        val:{}
    },
    /** Other recognized parameters: : [param, (ignored), value translation] */
    other:[['utme'],['el'],['ev'],['pa'],['cg1'],['pr1id'],['pr1nm'],['pr1ca'],['ep.outbound'],['ep.file_name'],['ep.file_extension'],['ep.menu_category_1'],['ep.menu_category_2'],['ep.menu_category_3'],['ep.menu_category_4'],['ep.menu_category_5'],['en (1)'],['epn.value (1)'],['en (2)'],['epn.value (2)'],['en (3)'],['epn.value (3)'],['en (4)'],['epn.value (4)']]       
},
/** 
 * Space dictionary 
 */
space:
{
    /** List of properties for which tags must not be displayed */
    filtered:[],
    /** List of properties that can use Custom variable naming as defined in ts.detail.cvar.val */
    known:[]
},
/** 
 * Parameters dictionary 
 */
param:
{
    '_c':'Is Conversion?',
    '_dbg':'Debug View?',
    '_ecid':'European Consent Mode Enabled ID',
    '_ee':'External Event',
    '_et':'Engagement Time',
    '_eu':'Event Usage',
    '_fid':'Firebase Id',
    '_fplc':'First Party Linker Cookie',
    '_fv':'First Visit',
    '_gaz':'Create Google Join',
    '_geo':'Geo Granularity',
    '_gid':'MD5 hash of page path',
    '_glv':'Google Linker Valid?',
    '_nsi':'New Session Id',
    '_p':'Random Page Load Hash',
    '_r':'Redirected Request?',
    '_rdi':'Redact Device Info',
    '_rnd':'Gclid Deduper',
    '_s':'Hit Counter',
    '_ss':'Session Start',
    '_tu':'Transport Url (hash)',
    '_u':'Usage info (features used)',
    '_uc':'User Country',
    '_uei':'_uei',
    '_utma':'Visitor Cookie',
    '_utmb':'Session Cookie',
    '_utmc':'Session Cookie',
    '_utmht':'Cookie value',
    '_utmv':'Custom Variable Cookie',
    '_utmz':'Campaign Cookie',
    '_v':'SDK Version',
    '_z':'_z',
    'a':'Adsense Link',
    'af':'Item Affiliation',
    'aid':'Application ID',
    'aiid':'Application Installation ID',
    'aip':'Anonymize IP?',
    'an':'Application Name',
    'are':'Attribution Reporting',
    'av':'Application Version',
    'br':'Item Brand',
    'ca':'Item Category Hierarchy 1',
    'ca2':'Item Category Hierarchy 2',
    'ca3':'Item Category Hierarchy 3',
    'ca4':'Item Category Hierarchy 4',
    'ca5':'Item Category Hierarchy 5',
    'cc':'Campaign Content',
    'ccf':'Campaign Creative Format',
    'cd':'Screen Name',
    'cd_':'Custom Dimension',
    'cg_':'Content Group',
    'ci':'Campaign ID',
    'cid':'Client ID (random.timestamp)',
    'ck':'Campaign Keyword',
    'clt':'Content Load Time',
    'cm':'Campaign Medium',
    'cm_I_':'Custom metric $0',
    'cmt':'Campaign Marketing Tactic',
    'cn':'Campaign Name',
    'col':'Checkout Step Option',
    'cos':'Checkout Step',
    'cp':'Item Coupon',
    'cs':'Campaign Source',
    'cu':'Currency Code',
    'dclid':'Display Ads ID',
    'de':'Document Encoding',
    'dh':'Document Hostname',
    'dit':'DOM Interactive Time',
    'dl':'Page Location',
    'dma':'Digital Market Act',
    'dma_cps':'Digital Market Act - Core Platform Sharing: (s)earch, (y)outube, (p)lay, s(h)opping, (a)ds, (m)aps, all (o)pt',
    'dns':'DNS Time',
    'doubleclick':'Google Remarketing',
    'dp':'Path',
    'dr':'Document Referrer',
    'ds_I_':'Item $0 Discount',
    'ds':'Data Source',
    'dt':'Page Title',
    'ea':'Event Action',
    'ec':'Event Category',
    'edid':'Event Debug ID?',
    'el':'Event Label',
    'en':'Event Name',
    'en (_I_)':'Additional Event ($0)',
    'ep.affiliation':'Affiliation',
    'ep.file_extension':'File extension',
    'ep.file_name':'File name',
    'ep.link_id':'Link ID',
    'ep.link_text':'Link Ttext',
    'ep.link_url':'Link URL',
    'ep.outbound':'Outbound link',
    'epn.percent_scrolled':'Percent scrolled',
    'epn.shipping':'Transaction Shipping',
    'epn.tax':'Transaction Tax',
    'epn.value':'Value',
    'epn.value (_I_)':'Value ($0)',
    'ev':'Value',
    'exd':'Exception Description',
    'exf':'Exception Fatal?',
    'fl':'Flash version',
    'frm':'Is IFrame event?',
    'gcd':'Google Consent Default',
    'gcs':'Google Consent Status',
    'gcu':'Google Consent Update',
    'gcut':'Google Consent Update Type',
    'gdid':'Google Developer ID',
    'gdpr':'GDPR applies?',
    'gdpr_consent':'GDPR Vendors Lists IDs',
    'geoid':'Geographical Override',
    'gjid':'Tracking code version',
    'glcid':'Adwords ID',
    'gtm':'GTM Hash Info',
    'gtm_up':'gtm_up',
    'ic':'Item Code',
    'id':'Item Id',
    'il_I_nm':'Product Impression List $0 name',
    'il_I_pi_I_br':'List$0 Product$1 Impression Brand',
    'il_I_pi_I_ca':'List$0 Product$1 Impression Category',
    'il_I_pi_I_cd_I_':'List$0 Product$1 Impression Custom dimension $2',
    'il_I_pi_I_cm_I_':'List$0 Product$1 Impression Custom metric $2',
    'il_I_pi_I_id':'List$0 Product$1 Impression SKU',
    'il_I_pi_I_nm':'List$0 Product$1 Impression Name',
    'il_I_pi_I_pr':'List$0 Product$1 Impression Price',
    'il_I_pi_I_ps':'List$0 Product$1 Impression Position',
    'il_I_pi_I_va':'List$0 Product$1 Impression Variant',
    'in':'Item Name',
    'ip':'Item Unit Price',
    'iq':'Item Quantity',
    'ir':'Ignore Referrer',
    'iv':'Item Variation',
    'je':'Java Enabled?',
    'jid':'Join ID (GA <=> Display Ads)',
    'li':'Item List ID',
    'linkid':'Clicked DOM element ID',
    'ln':'Item List Name',
    'lo':'Location ID',
    'lp':'Item List Position',
    'ni':'Non Interaction',
    'npa':'Disable Advertising Personalization',
    'nsi':'New Session Id',
    'pa':'Product Action',
    'pal':'Product Action List',
    'pdt':'Page Download Time',
    'pi':'Promotion ID',
    'plt':'Page Load Time',
    'pn':'Promotion Name',
    'pr':'Item Price',
    'pr_I_':'Item $0',
    'pr_I_ (_I_)':'Item $0 ($1)',
    'pr_I_br':'Product$0 Brand',
    'pr_I_ca':'Product$0 Category',
    'pr_I_cd_I_':'Product$0 Custom Dimension $1',
    'pr_I_cm_I_':'Product$0 Custom Metric $1',
    'pr_I_id':'Product$0 SKU',
    'pr_I_nm':'Product$0 Name',
    'pr_I_pr':'Product$0 Price',
    'pr_I_ps':'Product$0 Position',
    'pr_I_qt':'Product$0 Quantity',
    'pr_I_va':'Product$0 Variant',
    'promoa':'Promotion Action',
    'promo_I_cr':'Promotion$0 Creative',
    'promo_I_id':'Promotion$0 ID',
    'promo_I_nm':'Promotion$0 Name',
    'promo_I_ps':'Promotion$0 Position',
    'pscdl':'Privacy Sandbox Cookie Deprecation Label',
    'qt':'Queue Time',
    'qt_I_':'Item $0 Quantity',
    'richsstsse':'Enrich Server Side GTM',    
    'rrt':'Redirect Response Time',
    'sa':'Social Action',
    'sc':'Session Control',
    'sct':'Session Count',
    'sd':'Screen Color Depth',
    'seg':'Session Engagment',
    'sid':'Session ID',
    'sn':'Social Network',
    'sr':'Screen Resolution',
    'srt':'Server Response Time',
    'sst.uc':'User Country',
    'st':'Social Action Target',
    't':'Tracking Type',
    'ta':'Transaction Affiliation',
    'tag_exp':'Tag Experiment (Google)',
    'tcc':'Transaction Coupon Code',
    'tcp':'TCP Connect Time',
    'tfd':'Time For DOM (page performance)',
    'ti':'Transaction ID',
    'tid':'Tracking ID (GA property)',
    'tr':'Transaction Revenue',
    'ts':'Transaction Shipping',
    'tt':'Transaction Tax',
    'tt_GA4':'Traffic Type',
    'ua':'User Agent override',
    'uaa':'User Agent Architecture',
    'uab':'User Agent Bitness',
    'uafvl':'User Agent Full Version List',
    'uam':'User Agent Model',
    'uamb':'User Agent Mobile',
    'uap':'User Agent Platform',
    'uapv':'User Agent Platform Version',
    'uaw':'User Agent WOW64',
    'uid':'User Id',
    'uip':'User IP override',
    'ul':'User Language',
    'us_privacy':'US Privacy Signal',
    'utc':'User Timing Category',
    'utl':'User Timing Label',
    'utt':'User Timing Time',
    'utv':'User Timing Variable Name',
    'utmac':'Google Analytics property',
    'utmcc':'Visitor and Campaign cookies',
    'utmccn':'Campaign Name',
    'utmcct':'Campaign Content',
    'utmcmd':'Campaign Medium',
    'utmcn':'New Campaign?',
    'utmcr':'Repeat Campaign?',
    'utmcs':'Document Encoding',
    'utmcsr':'Campaign Source',
    'utmctr':'Campaign Keyword',
    'utmdt':'Page Title',
    'utme':'Extensible',
    'utmfl':'Flash version',
    'utmhid':'Cache buster',
    'utmhn':'Host name',
    'utmht':'Timestamp',
    'utmipc ':'Item Code',
    'utmipn':'Item Name',
    'utmipr':'Item Unit Price',
    'utmiqt':'Item Quantity',
    'utmiva':'Item Variation',
    'utmje':'Java enabled?',
    'utmjid':'Join ID (GA <=> Display Ads)',
    'utmn':'Cache buster',
    'utmp':'Document Path',
    'utmr':'Document Referrer',
    'utmredir':'Redirected request',
    'utms':'Hit Sequence',
    'utmsa':'Social Action',
    'utmsc':'Screen Color Depth',
    'utmsid':'Social Destination',
    'utmsn':'Social Network Name',
    'utmsr':'Screen Resolution',
    'utmt':'Tracking Type',
    'utmtci':'Billing City',
    'utmtco':'Billing Country',
    'utmtid':'Transaction ID',
    'utmtrg':'Billing Region',
    'utmtsp':'Transaction Shipping',
    'utmtst':'Transaction Affiliation',
    'utmtto':'Transaction Revenue',
    'utmttx':'Transaction Tax',
    'utmu':'Verification Code',
    'utmul':'Browser Language',
    'utmvp':'Viewport Resolution',
    'utmwv':'SDK Version',
    'v':'Protocol Version',
    'va':'Item Variant',
    'vp':'Viewport Resolution',
    'xid':'Experiment ID',
    'xvar':'Experiment Variant',
    'z':'Cache buster'  
}
};